import type { NextPage } from "next";
import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

type HeaderType = {
  headerTitle: string;
  headerImage: any;
  headerSubtitle: string;
};

const Home: NextPage = () => {
  const [header, setHeader] = useState<HeaderType>({
    headerTitle: "",
    headerImage: null,
    headerSubtitle: "",
  });

  const query = `
  {
    headerCollection {
      items {
        headerTitle
        headerImage {
          title
          description
          contentType
          fileName
          size
          url
          width
          height
        }
        headerSubtitle
      }
    }
  }
  `;

  const myLoader = ({}) => {
    return header.headerImage?.url;
  };
  useEffect(() => {
    fetch(
      `https://graphql.contentful.com/content/v1/spaces/${process.env.NEXT_PUBLIC_SPACE_ID}/`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          // Authenticate the request
          Authorization: `Bearer ${process.env.NEXT_PUBLIC_ACCESS_TOKEN}`,
        },
        // send the GraphQL query
        body: JSON.stringify({ query }),
      }
    )
      .then((response) => response.json())
      .then(({ data, errors }) => {
        if (errors) {
          console.error(errors);
        }

        // rerender the entire component with new data
        setHeader(data.headerCollection.items[0]);
      });
  }, [query]);
  console.log(header);

  if (!header) {
    return <>Loading...</>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Contentful Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">{header.headerTitle}</a>
        </h1>
        <h3 className={styles.description}>{header.headerSubtitle}</h3>
      </header>
      <main className={styles.main}>
        <Image
          src={header.headerImage?.url}
          loader={myLoader}
          layout="responsive"
          width={400}
          height={500}
          alt="FunkeyBild"
        />
      </main>
    </div>
  );
};

export default Home;
